[tools]
selene = { source = "Kampfkarren/selene", version = "x" }
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
remodel = { source = "rojo-rbx/remodel", version = "0.9.0" }
wally = { source = "UpliftGames/wally", version = "0.2.1" }
