gitRepoUrl = "https://github.com/AnimalStudio-Official/Knit2"


classOrder = [
	"CrystalServer",
	"CrystalClient"
]



[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Lightweight game framework for Roblox"
favicon = "/favicon.png"
