gitRepoUrl = "https://github.com/AnimalStudio-Official/Knit2"



[[classOrder]]
section = "Sectionname"
classes = ["CrystalServer", "CrystalClient"]


[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Lightweight game framework for Roblox"
favicon = "/favicon.png"
