[[task.spawn.args]]
type = "function"
[[task.spawn.args]]
required = false
type = "..."

[[task.defer.args]]
type = "function"
[[task.defer.args]]
required = false
type = "..."

[[task.wait.args]]
required = false
type = "number"

[[task.delay.args]]
type = "number"
[[task.delay.args]]
type = "function"
[[task.delay.args]]
required = false
type = "..."
