[package]
name = "sleitnick/knit"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@1.0.1"
Signal = "sleitnick/signal@1.0.0"
TableUtil = "sleitnick/table-util@1.0.0"
